name: CI

on:
  push:
    branches: '*'
    tags: '*'
  schedule:
    # run at 6AM & 6PM UTC
    - cron:  '0 6,18 * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: actions/hello-world-composite-run-steps-action@v1
      with:
        who-to-greet: 'Mona the Octocat'
        
  Build:
    env:
      APP_NAME: MicroVector
      TEST_NAME: MicroVector
    runs-on: macos-latest
    environment: Signing
    timeout-minutes: 120
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2
        with:
          submodules: true

      # cannot test until macos-11.0 is available in GitHub Actions
      #- name: Framework Tests
      #  run: xcodebuild test -scheme ${{ env.TEST_NAME }}
      #- name: App Tests
      #  run: xcodebuild test -scheme ${{ env.APP_NAME }}

      - id: foo
        uses: hubomatic/hubomat@v3
        with:
          who-to-greet: 'Yoyo the Octycat'
